// Code generated by ent, DO NOT EDIT.

package discorduser

import (
	"sev0/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldContainsFold(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEQ(FieldUsername, v))
}

// GlobalName applies equality check predicate on the "global_name" field. It's identical to GlobalNameEQ.
func GlobalName(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEQ(FieldGlobalName, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldContainsFold(FieldUsername, v))
}

// GlobalNameEQ applies the EQ predicate on the "global_name" field.
func GlobalNameEQ(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEQ(FieldGlobalName, v))
}

// GlobalNameNEQ applies the NEQ predicate on the "global_name" field.
func GlobalNameNEQ(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldNEQ(FieldGlobalName, v))
}

// GlobalNameIn applies the In predicate on the "global_name" field.
func GlobalNameIn(vs ...string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldIn(FieldGlobalName, vs...))
}

// GlobalNameNotIn applies the NotIn predicate on the "global_name" field.
func GlobalNameNotIn(vs ...string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldNotIn(FieldGlobalName, vs...))
}

// GlobalNameGT applies the GT predicate on the "global_name" field.
func GlobalNameGT(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldGT(FieldGlobalName, v))
}

// GlobalNameGTE applies the GTE predicate on the "global_name" field.
func GlobalNameGTE(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldGTE(FieldGlobalName, v))
}

// GlobalNameLT applies the LT predicate on the "global_name" field.
func GlobalNameLT(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldLT(FieldGlobalName, v))
}

// GlobalNameLTE applies the LTE predicate on the "global_name" field.
func GlobalNameLTE(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldLTE(FieldGlobalName, v))
}

// GlobalNameContains applies the Contains predicate on the "global_name" field.
func GlobalNameContains(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldContains(FieldGlobalName, v))
}

// GlobalNameHasPrefix applies the HasPrefix predicate on the "global_name" field.
func GlobalNameHasPrefix(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldHasPrefix(FieldGlobalName, v))
}

// GlobalNameHasSuffix applies the HasSuffix predicate on the "global_name" field.
func GlobalNameHasSuffix(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldHasSuffix(FieldGlobalName, v))
}

// GlobalNameEqualFold applies the EqualFold predicate on the "global_name" field.
func GlobalNameEqualFold(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldEqualFold(FieldGlobalName, v))
}

// GlobalNameContainsFold applies the ContainsFold predicate on the "global_name" field.
func GlobalNameContainsFold(v string) predicate.DiscordUser {
	return predicate.DiscordUser(sql.FieldContainsFold(FieldGlobalName, v))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.DiscordUser {
	return predicate.DiscordUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.DiscordMessage) predicate.DiscordUser {
	return predicate.DiscordUser(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DiscordUser) predicate.DiscordUser {
	return predicate.DiscordUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DiscordUser) predicate.DiscordUser {
	return predicate.DiscordUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DiscordUser) predicate.DiscordUser {
	return predicate.DiscordUser(sql.NotPredicates(p))
}
