// Code generated by ent, DO NOT EDIT.

package discordmessageembedding

import (
	"sev0/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldContainsFold(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldMessageID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldModel, v))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldEmbedding, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldCreatedAt, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldContainsFold(FieldMessageID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldContainsFold(FieldModel, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.Vector) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLTE(FieldEmbedding, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.DiscordMessage) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DiscordMessageEmbedding) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DiscordMessageEmbedding) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DiscordMessageEmbedding) predicate.DiscordMessageEmbedding {
	return predicate.DiscordMessageEmbedding(sql.NotPredicates(p))
}
