// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DiscordMessagesColumns holds the columns for the "discord_messages" table.
	DiscordMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "edited_timestamp", Type: field.TypeTime, Nullable: true},
		{Name: "author_id", Type: field.TypeString},
	}
	// DiscordMessagesTable holds the schema information for the "discord_messages" table.
	DiscordMessagesTable = &schema.Table{
		Name:       "discord_messages",
		Columns:    DiscordMessagesColumns,
		PrimaryKey: []*schema.Column{DiscordMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "discord_messages_discord_users_messages",
				Columns:    []*schema.Column{DiscordMessagesColumns[4]},
				RefColumns: []*schema.Column{DiscordUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DiscordUsersColumns holds the columns for the "discord_users" table.
	DiscordUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "global_name", Type: field.TypeString},
	}
	// DiscordUsersTable holds the schema information for the "discord_users" table.
	DiscordUsersTable = &schema.Table{
		Name:       "discord_users",
		Columns:    DiscordUsersColumns,
		PrimaryKey: []*schema.Column{DiscordUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiscordMessagesTable,
		DiscordUsersTable,
	}
)

func init() {
	DiscordMessagesTable.ForeignKeys[0].RefTable = DiscordUsersTable
}
