// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DiscordMessagesColumns holds the columns for the "discord_messages" table.
	DiscordMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "edited_timestamp", Type: field.TypeTime, Nullable: true},
		{Name: "author_id", Type: field.TypeString},
	}
	// DiscordMessagesTable holds the schema information for the "discord_messages" table.
	DiscordMessagesTable = &schema.Table{
		Name:       "discord_messages",
		Columns:    DiscordMessagesColumns,
		PrimaryKey: []*schema.Column{DiscordMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "discord_messages_discord_users_messages",
				Columns:    []*schema.Column{DiscordMessagesColumns[4]},
				RefColumns: []*schema.Column{DiscordUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "discordmessage_timestamp",
				Unique:  false,
				Columns: []*schema.Column{DiscordMessagesColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						DiscordMessagesColumns[2].Name: true,
					},
				},
			},
		},
	}
	// DiscordMessageEmbeddingsColumns holds the columns for the "discord_message_embeddings" table.
	DiscordMessageEmbeddingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "embedding", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "vector"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "message_id", Type: field.TypeString},
	}
	// DiscordMessageEmbeddingsTable holds the schema information for the "discord_message_embeddings" table.
	DiscordMessageEmbeddingsTable = &schema.Table{
		Name:       "discord_message_embeddings",
		Columns:    DiscordMessageEmbeddingsColumns,
		PrimaryKey: []*schema.Column{DiscordMessageEmbeddingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "discord_message_embeddings_discord_messages_embeddings",
				Columns:    []*schema.Column{DiscordMessageEmbeddingsColumns[4]},
				RefColumns: []*schema.Column{DiscordMessagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "discordmessageembedding_message_id_model",
				Unique:  true,
				Columns: []*schema.Column{DiscordMessageEmbeddingsColumns[4], DiscordMessageEmbeddingsColumns[1]},
			},
		},
	}
	// DiscordUsersColumns holds the columns for the "discord_users" table.
	DiscordUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "global_name", Type: field.TypeString},
	}
	// DiscordUsersTable holds the schema information for the "discord_users" table.
	DiscordUsersTable = &schema.Table{
		Name:       "discord_users",
		Columns:    DiscordUsersColumns,
		PrimaryKey: []*schema.Column{DiscordUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiscordMessagesTable,
		DiscordMessageEmbeddingsTable,
		DiscordUsersTable,
	}
)

func init() {
	DiscordMessagesTable.ForeignKeys[0].RefTable = DiscordUsersTable
	DiscordMessageEmbeddingsTable.ForeignKeys[0].RefTable = DiscordMessagesTable
}
