// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"sev0/ent/migrate"

	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DiscordMessage is the client for interacting with the DiscordMessage builders.
	DiscordMessage *DiscordMessageClient
	// DiscordUser is the client for interacting with the DiscordUser builders.
	DiscordUser *DiscordUserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DiscordMessage = NewDiscordMessageClient(c.config)
	c.DiscordUser = NewDiscordUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		DiscordMessage: NewDiscordMessageClient(cfg),
		DiscordUser:    NewDiscordUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		DiscordMessage: NewDiscordMessageClient(cfg),
		DiscordUser:    NewDiscordUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DiscordMessage.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DiscordMessage.Use(hooks...)
	c.DiscordUser.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DiscordMessage.Intercept(interceptors...)
	c.DiscordUser.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DiscordMessageMutation:
		return c.DiscordMessage.mutate(ctx, m)
	case *DiscordUserMutation:
		return c.DiscordUser.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DiscordMessageClient is a client for the DiscordMessage schema.
type DiscordMessageClient struct {
	config
}

// NewDiscordMessageClient returns a client for the DiscordMessage from the given config.
func NewDiscordMessageClient(c config) *DiscordMessageClient {
	return &DiscordMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `discordmessage.Hooks(f(g(h())))`.
func (c *DiscordMessageClient) Use(hooks ...Hook) {
	c.hooks.DiscordMessage = append(c.hooks.DiscordMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `discordmessage.Intercept(f(g(h())))`.
func (c *DiscordMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.DiscordMessage = append(c.inters.DiscordMessage, interceptors...)
}

// Create returns a builder for creating a DiscordMessage entity.
func (c *DiscordMessageClient) Create() *DiscordMessageCreate {
	mutation := newDiscordMessageMutation(c.config, OpCreate)
	return &DiscordMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DiscordMessage entities.
func (c *DiscordMessageClient) CreateBulk(builders ...*DiscordMessageCreate) *DiscordMessageCreateBulk {
	return &DiscordMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DiscordMessageClient) MapCreateBulk(slice any, setFunc func(*DiscordMessageCreate, int)) *DiscordMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DiscordMessageCreateBulk{err: fmt.Errorf("calling to DiscordMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DiscordMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DiscordMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DiscordMessage.
func (c *DiscordMessageClient) Update() *DiscordMessageUpdate {
	mutation := newDiscordMessageMutation(c.config, OpUpdate)
	return &DiscordMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DiscordMessageClient) UpdateOne(_m *DiscordMessage) *DiscordMessageUpdateOne {
	mutation := newDiscordMessageMutation(c.config, OpUpdateOne, withDiscordMessage(_m))
	return &DiscordMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DiscordMessageClient) UpdateOneID(id string) *DiscordMessageUpdateOne {
	mutation := newDiscordMessageMutation(c.config, OpUpdateOne, withDiscordMessageID(id))
	return &DiscordMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DiscordMessage.
func (c *DiscordMessageClient) Delete() *DiscordMessageDelete {
	mutation := newDiscordMessageMutation(c.config, OpDelete)
	return &DiscordMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DiscordMessageClient) DeleteOne(_m *DiscordMessage) *DiscordMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DiscordMessageClient) DeleteOneID(id string) *DiscordMessageDeleteOne {
	builder := c.Delete().Where(discordmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DiscordMessageDeleteOne{builder}
}

// Query returns a query builder for DiscordMessage.
func (c *DiscordMessageClient) Query() *DiscordMessageQuery {
	return &DiscordMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDiscordMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a DiscordMessage entity by its id.
func (c *DiscordMessageClient) Get(ctx context.Context, id string) (*DiscordMessage, error) {
	return c.Query().Where(discordmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DiscordMessageClient) GetX(ctx context.Context, id string) *DiscordMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a DiscordMessage.
func (c *DiscordMessageClient) QueryUser(_m *DiscordMessage) *DiscordUserQuery {
	query := (&DiscordUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(discordmessage.Table, discordmessage.FieldID, id),
			sqlgraph.To(discorduser.Table, discorduser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, discordmessage.UserTable, discordmessage.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DiscordMessageClient) Hooks() []Hook {
	return c.hooks.DiscordMessage
}

// Interceptors returns the client interceptors.
func (c *DiscordMessageClient) Interceptors() []Interceptor {
	return c.inters.DiscordMessage
}

func (c *DiscordMessageClient) mutate(ctx context.Context, m *DiscordMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DiscordMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DiscordMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DiscordMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DiscordMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DiscordMessage mutation op: %q", m.Op())
	}
}

// DiscordUserClient is a client for the DiscordUser schema.
type DiscordUserClient struct {
	config
}

// NewDiscordUserClient returns a client for the DiscordUser from the given config.
func NewDiscordUserClient(c config) *DiscordUserClient {
	return &DiscordUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `discorduser.Hooks(f(g(h())))`.
func (c *DiscordUserClient) Use(hooks ...Hook) {
	c.hooks.DiscordUser = append(c.hooks.DiscordUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `discorduser.Intercept(f(g(h())))`.
func (c *DiscordUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.DiscordUser = append(c.inters.DiscordUser, interceptors...)
}

// Create returns a builder for creating a DiscordUser entity.
func (c *DiscordUserClient) Create() *DiscordUserCreate {
	mutation := newDiscordUserMutation(c.config, OpCreate)
	return &DiscordUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DiscordUser entities.
func (c *DiscordUserClient) CreateBulk(builders ...*DiscordUserCreate) *DiscordUserCreateBulk {
	return &DiscordUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DiscordUserClient) MapCreateBulk(slice any, setFunc func(*DiscordUserCreate, int)) *DiscordUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DiscordUserCreateBulk{err: fmt.Errorf("calling to DiscordUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DiscordUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DiscordUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DiscordUser.
func (c *DiscordUserClient) Update() *DiscordUserUpdate {
	mutation := newDiscordUserMutation(c.config, OpUpdate)
	return &DiscordUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DiscordUserClient) UpdateOne(_m *DiscordUser) *DiscordUserUpdateOne {
	mutation := newDiscordUserMutation(c.config, OpUpdateOne, withDiscordUser(_m))
	return &DiscordUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DiscordUserClient) UpdateOneID(id string) *DiscordUserUpdateOne {
	mutation := newDiscordUserMutation(c.config, OpUpdateOne, withDiscordUserID(id))
	return &DiscordUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DiscordUser.
func (c *DiscordUserClient) Delete() *DiscordUserDelete {
	mutation := newDiscordUserMutation(c.config, OpDelete)
	return &DiscordUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DiscordUserClient) DeleteOne(_m *DiscordUser) *DiscordUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DiscordUserClient) DeleteOneID(id string) *DiscordUserDeleteOne {
	builder := c.Delete().Where(discorduser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DiscordUserDeleteOne{builder}
}

// Query returns a query builder for DiscordUser.
func (c *DiscordUserClient) Query() *DiscordUserQuery {
	return &DiscordUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDiscordUser},
		inters: c.Interceptors(),
	}
}

// Get returns a DiscordUser entity by its id.
func (c *DiscordUserClient) Get(ctx context.Context, id string) (*DiscordUser, error) {
	return c.Query().Where(discorduser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DiscordUserClient) GetX(ctx context.Context, id string) *DiscordUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMessages queries the messages edge of a DiscordUser.
func (c *DiscordUserClient) QueryMessages(_m *DiscordUser) *DiscordMessageQuery {
	query := (&DiscordMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(discorduser.Table, discorduser.FieldID, id),
			sqlgraph.To(discordmessage.Table, discordmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, discorduser.MessagesTable, discorduser.MessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DiscordUserClient) Hooks() []Hook {
	return c.hooks.DiscordUser
}

// Interceptors returns the client interceptors.
func (c *DiscordUserClient) Interceptors() []Interceptor {
	return c.inters.DiscordUser
}

func (c *DiscordUserClient) mutate(ctx context.Context, m *DiscordUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DiscordUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DiscordUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DiscordUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DiscordUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DiscordUser mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DiscordMessage, DiscordUser []ent.Hook
	}
	inters struct {
		DiscordMessage, DiscordUser []ent.Interceptor
	}
)
