// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discordmessageembedding"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	pgvector "github.com/pgvector/pgvector-go"
)

// DiscordMessageEmbeddingCreate is the builder for creating a DiscordMessageEmbedding entity.
type DiscordMessageEmbeddingCreate struct {
	config
	mutation *DiscordMessageEmbeddingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessageID sets the "message_id" field.
func (_c *DiscordMessageEmbeddingCreate) SetMessageID(v string) *DiscordMessageEmbeddingCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *DiscordMessageEmbeddingCreate) SetModel(v string) *DiscordMessageEmbeddingCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *DiscordMessageEmbeddingCreate) SetEmbedding(v pgvector.Vector) *DiscordMessageEmbeddingCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DiscordMessageEmbeddingCreate) SetCreatedAt(v time.Time) *DiscordMessageEmbeddingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DiscordMessageEmbeddingCreate) SetNillableCreatedAt(v *time.Time) *DiscordMessageEmbeddingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DiscordMessageEmbeddingCreate) SetID(v string) *DiscordMessageEmbeddingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetMessage sets the "message" edge to the DiscordMessage entity.
func (_c *DiscordMessageEmbeddingCreate) SetMessage(v *DiscordMessage) *DiscordMessageEmbeddingCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the DiscordMessageEmbeddingMutation object of the builder.
func (_c *DiscordMessageEmbeddingCreate) Mutation() *DiscordMessageEmbeddingMutation {
	return _c.mutation
}

// Save creates the DiscordMessageEmbedding in the database.
func (_c *DiscordMessageEmbeddingCreate) Save(ctx context.Context) (*DiscordMessageEmbedding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordMessageEmbeddingCreate) SaveX(ctx context.Context) *DiscordMessageEmbedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordMessageEmbeddingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordMessageEmbeddingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiscordMessageEmbeddingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := discordmessageembedding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordMessageEmbeddingCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "DiscordMessageEmbedding.message_id"`)}
	}
	if v, ok := _c.mutation.MessageID(); ok {
		if err := discordmessageembedding.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "DiscordMessageEmbedding.message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "DiscordMessageEmbedding.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := discordmessageembedding.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DiscordMessageEmbedding.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Embedding(); !ok {
		return &ValidationError{Name: "embedding", err: errors.New(`ent: missing required field "DiscordMessageEmbedding.embedding"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DiscordMessageEmbedding.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := discordmessageembedding.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DiscordMessageEmbedding.id": %w`, err)}
		}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "DiscordMessageEmbedding.message"`)}
	}
	return nil
}

func (_c *DiscordMessageEmbeddingCreate) sqlSave(ctx context.Context) (*DiscordMessageEmbedding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DiscordMessageEmbedding.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordMessageEmbeddingCreate) createSpec() (*DiscordMessageEmbedding, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordMessageEmbedding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discordmessageembedding.Table, sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(discordmessageembedding.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(discordmessageembedding.FieldEmbedding, field.TypeOther, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(discordmessageembedding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discordmessageembedding.MessageTable,
			Columns: []string{discordmessageembedding.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordMessageEmbedding.Create().
//		SetMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordMessageEmbeddingUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordMessageEmbeddingCreate) OnConflict(opts ...sql.ConflictOption) *DiscordMessageEmbeddingUpsertOne {
	_c.conflict = opts
	return &DiscordMessageEmbeddingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordMessageEmbedding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordMessageEmbeddingCreate) OnConflictColumns(columns ...string) *DiscordMessageEmbeddingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordMessageEmbeddingUpsertOne{
		create: _c,
	}
}

type (
	// DiscordMessageEmbeddingUpsertOne is the builder for "upsert"-ing
	//  one DiscordMessageEmbedding node.
	DiscordMessageEmbeddingUpsertOne struct {
		create *DiscordMessageEmbeddingCreate
	}

	// DiscordMessageEmbeddingUpsert is the "OnConflict" setter.
	DiscordMessageEmbeddingUpsert struct {
		*sql.UpdateSet
	}
)

// SetEmbedding sets the "embedding" field.
func (u *DiscordMessageEmbeddingUpsert) SetEmbedding(v pgvector.Vector) *DiscordMessageEmbeddingUpsert {
	u.Set(discordmessageembedding.FieldEmbedding, v)
	return u
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *DiscordMessageEmbeddingUpsert) UpdateEmbedding() *DiscordMessageEmbeddingUpsert {
	u.SetExcluded(discordmessageembedding.FieldEmbedding)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DiscordMessageEmbedding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(discordmessageembedding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiscordMessageEmbeddingUpsertOne) UpdateNewValues() *DiscordMessageEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(discordmessageembedding.FieldID)
		}
		if _, exists := u.create.mutation.MessageID(); exists {
			s.SetIgnore(discordmessageembedding.FieldMessageID)
		}
		if _, exists := u.create.mutation.Model(); exists {
			s.SetIgnore(discordmessageembedding.FieldModel)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(discordmessageembedding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordMessageEmbedding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DiscordMessageEmbeddingUpsertOne) Ignore() *DiscordMessageEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordMessageEmbeddingUpsertOne) DoNothing() *DiscordMessageEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordMessageEmbeddingCreate.OnConflict
// documentation for more info.
func (u *DiscordMessageEmbeddingUpsertOne) Update(set func(*DiscordMessageEmbeddingUpsert)) *DiscordMessageEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordMessageEmbeddingUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmbedding sets the "embedding" field.
func (u *DiscordMessageEmbeddingUpsertOne) SetEmbedding(v pgvector.Vector) *DiscordMessageEmbeddingUpsertOne {
	return u.Update(func(s *DiscordMessageEmbeddingUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *DiscordMessageEmbeddingUpsertOne) UpdateEmbedding() *DiscordMessageEmbeddingUpsertOne {
	return u.Update(func(s *DiscordMessageEmbeddingUpsert) {
		s.UpdateEmbedding()
	})
}

// Exec executes the query.
func (u *DiscordMessageEmbeddingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordMessageEmbeddingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordMessageEmbeddingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DiscordMessageEmbeddingUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DiscordMessageEmbeddingUpsertOne.ID is not supported by MySQL driver. Use DiscordMessageEmbeddingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DiscordMessageEmbeddingUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DiscordMessageEmbeddingCreateBulk is the builder for creating many DiscordMessageEmbedding entities in bulk.
type DiscordMessageEmbeddingCreateBulk struct {
	config
	err      error
	builders []*DiscordMessageEmbeddingCreate
	conflict []sql.ConflictOption
}

// Save creates the DiscordMessageEmbedding entities in the database.
func (_c *DiscordMessageEmbeddingCreateBulk) Save(ctx context.Context) ([]*DiscordMessageEmbedding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordMessageEmbedding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordMessageEmbeddingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordMessageEmbeddingCreateBulk) SaveX(ctx context.Context) []*DiscordMessageEmbedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordMessageEmbeddingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordMessageEmbeddingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordMessageEmbedding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordMessageEmbeddingUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordMessageEmbeddingCreateBulk) OnConflict(opts ...sql.ConflictOption) *DiscordMessageEmbeddingUpsertBulk {
	_c.conflict = opts
	return &DiscordMessageEmbeddingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordMessageEmbedding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordMessageEmbeddingCreateBulk) OnConflictColumns(columns ...string) *DiscordMessageEmbeddingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordMessageEmbeddingUpsertBulk{
		create: _c,
	}
}

// DiscordMessageEmbeddingUpsertBulk is the builder for "upsert"-ing
// a bulk of DiscordMessageEmbedding nodes.
type DiscordMessageEmbeddingUpsertBulk struct {
	create *DiscordMessageEmbeddingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DiscordMessageEmbedding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(discordmessageembedding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiscordMessageEmbeddingUpsertBulk) UpdateNewValues() *DiscordMessageEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(discordmessageembedding.FieldID)
			}
			if _, exists := b.mutation.MessageID(); exists {
				s.SetIgnore(discordmessageembedding.FieldMessageID)
			}
			if _, exists := b.mutation.Model(); exists {
				s.SetIgnore(discordmessageembedding.FieldModel)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(discordmessageembedding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordMessageEmbedding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DiscordMessageEmbeddingUpsertBulk) Ignore() *DiscordMessageEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordMessageEmbeddingUpsertBulk) DoNothing() *DiscordMessageEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordMessageEmbeddingCreateBulk.OnConflict
// documentation for more info.
func (u *DiscordMessageEmbeddingUpsertBulk) Update(set func(*DiscordMessageEmbeddingUpsert)) *DiscordMessageEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordMessageEmbeddingUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmbedding sets the "embedding" field.
func (u *DiscordMessageEmbeddingUpsertBulk) SetEmbedding(v pgvector.Vector) *DiscordMessageEmbeddingUpsertBulk {
	return u.Update(func(s *DiscordMessageEmbeddingUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *DiscordMessageEmbeddingUpsertBulk) UpdateEmbedding() *DiscordMessageEmbeddingUpsertBulk {
	return u.Update(func(s *DiscordMessageEmbeddingUpsert) {
		s.UpdateEmbedding()
	})
}

// Exec executes the query.
func (u *DiscordMessageEmbeddingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DiscordMessageEmbeddingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordMessageEmbeddingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordMessageEmbeddingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
