// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordMessageCreate is the builder for creating a DiscordMessage entity.
type DiscordMessageCreate struct {
	config
	mutation *DiscordMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContent sets the "content" field.
func (_c *DiscordMessageCreate) SetContent(v string) *DiscordMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *DiscordMessageCreate) SetAuthorID(v string) *DiscordMessageCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *DiscordMessageCreate) SetTimestamp(v time.Time) *DiscordMessageCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (_c *DiscordMessageCreate) SetEditedTimestamp(v time.Time) *DiscordMessageCreate {
	_c.mutation.SetEditedTimestamp(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DiscordMessageCreate) SetID(v string) *DiscordMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the DiscordUser entity by ID.
func (_c *DiscordMessageCreate) SetUserID(id string) *DiscordMessageCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the DiscordUser entity.
func (_c *DiscordMessageCreate) SetUser(v *DiscordUser) *DiscordMessageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DiscordMessageMutation object of the builder.
func (_c *DiscordMessageCreate) Mutation() *DiscordMessageMutation {
	return _c.mutation
}

// Save creates the DiscordMessage in the database.
func (_c *DiscordMessageCreate) Save(ctx context.Context) (*DiscordMessage, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordMessageCreate) SaveX(ctx context.Context) *DiscordMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordMessageCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "DiscordMessage.content"`)}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "DiscordMessage.author_id"`)}
	}
	if v, ok := _c.mutation.AuthorID(); ok {
		if err := discordmessage.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "DiscordMessage.author_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "DiscordMessage.timestamp"`)}
	}
	if _, ok := _c.mutation.EditedTimestamp(); !ok {
		return &ValidationError{Name: "edited_timestamp", err: errors.New(`ent: missing required field "DiscordMessage.edited_timestamp"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := discordmessage.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DiscordMessage.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DiscordMessage.user"`)}
	}
	return nil
}

func (_c *DiscordMessageCreate) sqlSave(ctx context.Context) (*DiscordMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DiscordMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordMessageCreate) createSpec() (*DiscordMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discordmessage.Table, sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(discordmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(discordmessage.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.EditedTimestamp(); ok {
		_spec.SetField(discordmessage.FieldEditedTimestamp, field.TypeTime, value)
		_node.EditedTimestamp = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discordmessage.UserTable,
			Columns: []string{discordmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordMessage.Create().
//		SetContent(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordMessageUpsert) {
//			SetContent(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordMessageCreate) OnConflict(opts ...sql.ConflictOption) *DiscordMessageUpsertOne {
	_c.conflict = opts
	return &DiscordMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordMessageCreate) OnConflictColumns(columns ...string) *DiscordMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordMessageUpsertOne{
		create: _c,
	}
}

type (
	// DiscordMessageUpsertOne is the builder for "upsert"-ing
	//  one DiscordMessage node.
	DiscordMessageUpsertOne struct {
		create *DiscordMessageCreate
	}

	// DiscordMessageUpsert is the "OnConflict" setter.
	DiscordMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetContent sets the "content" field.
func (u *DiscordMessageUpsert) SetContent(v string) *DiscordMessageUpsert {
	u.Set(discordmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *DiscordMessageUpsert) UpdateContent() *DiscordMessageUpsert {
	u.SetExcluded(discordmessage.FieldContent)
	return u
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (u *DiscordMessageUpsert) SetEditedTimestamp(v time.Time) *DiscordMessageUpsert {
	u.Set(discordmessage.FieldEditedTimestamp, v)
	return u
}

// UpdateEditedTimestamp sets the "edited_timestamp" field to the value that was provided on create.
func (u *DiscordMessageUpsert) UpdateEditedTimestamp() *DiscordMessageUpsert {
	u.SetExcluded(discordmessage.FieldEditedTimestamp)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DiscordMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(discordmessage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiscordMessageUpsertOne) UpdateNewValues() *DiscordMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(discordmessage.FieldID)
		}
		if _, exists := u.create.mutation.AuthorID(); exists {
			s.SetIgnore(discordmessage.FieldAuthorID)
		}
		if _, exists := u.create.mutation.Timestamp(); exists {
			s.SetIgnore(discordmessage.FieldTimestamp)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DiscordMessageUpsertOne) Ignore() *DiscordMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordMessageUpsertOne) DoNothing() *DiscordMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordMessageCreate.OnConflict
// documentation for more info.
func (u *DiscordMessageUpsertOne) Update(set func(*DiscordMessageUpsert)) *DiscordMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetContent sets the "content" field.
func (u *DiscordMessageUpsertOne) SetContent(v string) *DiscordMessageUpsertOne {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *DiscordMessageUpsertOne) UpdateContent() *DiscordMessageUpsertOne {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.UpdateContent()
	})
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (u *DiscordMessageUpsertOne) SetEditedTimestamp(v time.Time) *DiscordMessageUpsertOne {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.SetEditedTimestamp(v)
	})
}

// UpdateEditedTimestamp sets the "edited_timestamp" field to the value that was provided on create.
func (u *DiscordMessageUpsertOne) UpdateEditedTimestamp() *DiscordMessageUpsertOne {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.UpdateEditedTimestamp()
	})
}

// Exec executes the query.
func (u *DiscordMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DiscordMessageUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DiscordMessageUpsertOne.ID is not supported by MySQL driver. Use DiscordMessageUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DiscordMessageUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DiscordMessageCreateBulk is the builder for creating many DiscordMessage entities in bulk.
type DiscordMessageCreateBulk struct {
	config
	err      error
	builders []*DiscordMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the DiscordMessage entities in the database.
func (_c *DiscordMessageCreateBulk) Save(ctx context.Context) ([]*DiscordMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordMessageCreateBulk) SaveX(ctx context.Context) []*DiscordMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordMessageUpsert) {
//			SetContent(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *DiscordMessageUpsertBulk {
	_c.conflict = opts
	return &DiscordMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordMessageCreateBulk) OnConflictColumns(columns ...string) *DiscordMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordMessageUpsertBulk{
		create: _c,
	}
}

// DiscordMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of DiscordMessage nodes.
type DiscordMessageUpsertBulk struct {
	create *DiscordMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DiscordMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(discordmessage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiscordMessageUpsertBulk) UpdateNewValues() *DiscordMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(discordmessage.FieldID)
			}
			if _, exists := b.mutation.AuthorID(); exists {
				s.SetIgnore(discordmessage.FieldAuthorID)
			}
			if _, exists := b.mutation.Timestamp(); exists {
				s.SetIgnore(discordmessage.FieldTimestamp)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DiscordMessageUpsertBulk) Ignore() *DiscordMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordMessageUpsertBulk) DoNothing() *DiscordMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordMessageCreateBulk.OnConflict
// documentation for more info.
func (u *DiscordMessageUpsertBulk) Update(set func(*DiscordMessageUpsert)) *DiscordMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetContent sets the "content" field.
func (u *DiscordMessageUpsertBulk) SetContent(v string) *DiscordMessageUpsertBulk {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *DiscordMessageUpsertBulk) UpdateContent() *DiscordMessageUpsertBulk {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.UpdateContent()
	})
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (u *DiscordMessageUpsertBulk) SetEditedTimestamp(v time.Time) *DiscordMessageUpsertBulk {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.SetEditedTimestamp(v)
	})
}

// UpdateEditedTimestamp sets the "edited_timestamp" field to the value that was provided on create.
func (u *DiscordMessageUpsertBulk) UpdateEditedTimestamp() *DiscordMessageUpsertBulk {
	return u.Update(func(s *DiscordMessageUpsert) {
		s.UpdateEditedTimestamp()
	})
}

// Exec executes the query.
func (u *DiscordMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DiscordMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
