// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sev0/ent/discordmessageembedding"
	"sev0/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordMessageEmbeddingDelete is the builder for deleting a DiscordMessageEmbedding entity.
type DiscordMessageEmbeddingDelete struct {
	config
	hooks    []Hook
	mutation *DiscordMessageEmbeddingMutation
}

// Where appends a list predicates to the DiscordMessageEmbeddingDelete builder.
func (_d *DiscordMessageEmbeddingDelete) Where(ps ...predicate.DiscordMessageEmbedding) *DiscordMessageEmbeddingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiscordMessageEmbeddingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscordMessageEmbeddingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiscordMessageEmbeddingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discordmessageembedding.Table, sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiscordMessageEmbeddingDeleteOne is the builder for deleting a single DiscordMessageEmbedding entity.
type DiscordMessageEmbeddingDeleteOne struct {
	_d *DiscordMessageEmbeddingDelete
}

// Where appends a list predicates to the DiscordMessageEmbeddingDelete builder.
func (_d *DiscordMessageEmbeddingDeleteOne) Where(ps ...predicate.DiscordMessageEmbedding) *DiscordMessageEmbeddingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiscordMessageEmbeddingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discordmessageembedding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscordMessageEmbeddingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
