// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discordmessageembedding"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	pgvector "github.com/pgvector/pgvector-go"
)

// DiscordMessageEmbedding is the model entity for the DiscordMessageEmbedding schema.
type DiscordMessageEmbedding struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID string `json:"message_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Embedding holds the value of the "embedding" field.
	Embedding pgvector.Vector `json:"embedding,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiscordMessageEmbeddingQuery when eager-loading is set.
	Edges        DiscordMessageEmbeddingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DiscordMessageEmbeddingEdges holds the relations/edges for other nodes in the graph.
type DiscordMessageEmbeddingEdges struct {
	// Message holds the value of the message edge.
	Message *DiscordMessage `json:"message,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DiscordMessageEmbeddingEdges) MessageOrErr() (*DiscordMessage, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: discordmessage.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscordMessageEmbedding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discordmessageembedding.FieldEmbedding:
			values[i] = new(pgvector.Vector)
		case discordmessageembedding.FieldID, discordmessageembedding.FieldMessageID, discordmessageembedding.FieldModel:
			values[i] = new(sql.NullString)
		case discordmessageembedding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscordMessageEmbedding fields.
func (_m *DiscordMessageEmbedding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discordmessageembedding.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case discordmessageembedding.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		case discordmessageembedding.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case discordmessageembedding.FieldEmbedding:
			if value, ok := values[i].(*pgvector.Vector); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value != nil {
				_m.Embedding = *value
			}
		case discordmessageembedding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscordMessageEmbedding.
// This includes values selected through modifiers, order, etc.
func (_m *DiscordMessageEmbedding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the DiscordMessageEmbedding entity.
func (_m *DiscordMessageEmbedding) QueryMessage() *DiscordMessageQuery {
	return NewDiscordMessageEmbeddingClient(_m.config).QueryMessage(_m)
}

// Update returns a builder for updating this DiscordMessageEmbedding.
// Note that you need to call DiscordMessageEmbedding.Unwrap() before calling this method if this DiscordMessageEmbedding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscordMessageEmbedding) Update() *DiscordMessageEmbeddingUpdateOne {
	return NewDiscordMessageEmbeddingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscordMessageEmbedding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscordMessageEmbedding) Unwrap() *DiscordMessageEmbedding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscordMessageEmbedding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscordMessageEmbedding) String() string {
	var builder strings.Builder
	builder.WriteString("DiscordMessageEmbedding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("embedding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Embedding))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DiscordMessageEmbeddings is a parsable slice of DiscordMessageEmbedding.
type DiscordMessageEmbeddings []*DiscordMessageEmbedding
