// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordMessageCreate is the builder for creating a DiscordMessage entity.
type DiscordMessageCreate struct {
	config
	mutation *DiscordMessageMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (_c *DiscordMessageCreate) SetContent(v string) *DiscordMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *DiscordMessageCreate) SetAuthorID(v string) *DiscordMessageCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *DiscordMessageCreate) SetTimestamp(v time.Time) *DiscordMessageCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (_c *DiscordMessageCreate) SetEditedTimestamp(v time.Time) *DiscordMessageCreate {
	_c.mutation.SetEditedTimestamp(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DiscordMessageCreate) SetID(v string) *DiscordMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the DiscordUser entity by ID.
func (_c *DiscordMessageCreate) SetUserID(id string) *DiscordMessageCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the DiscordUser entity.
func (_c *DiscordMessageCreate) SetUser(v *DiscordUser) *DiscordMessageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DiscordMessageMutation object of the builder.
func (_c *DiscordMessageCreate) Mutation() *DiscordMessageMutation {
	return _c.mutation
}

// Save creates the DiscordMessage in the database.
func (_c *DiscordMessageCreate) Save(ctx context.Context) (*DiscordMessage, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordMessageCreate) SaveX(ctx context.Context) *DiscordMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordMessageCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "DiscordMessage.content"`)}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "DiscordMessage.author_id"`)}
	}
	if v, ok := _c.mutation.AuthorID(); ok {
		if err := discordmessage.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "DiscordMessage.author_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "DiscordMessage.timestamp"`)}
	}
	if _, ok := _c.mutation.EditedTimestamp(); !ok {
		return &ValidationError{Name: "edited_timestamp", err: errors.New(`ent: missing required field "DiscordMessage.edited_timestamp"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := discordmessage.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DiscordMessage.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DiscordMessage.user"`)}
	}
	return nil
}

func (_c *DiscordMessageCreate) sqlSave(ctx context.Context) (*DiscordMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DiscordMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordMessageCreate) createSpec() (*DiscordMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discordmessage.Table, sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(discordmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(discordmessage.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.EditedTimestamp(); ok {
		_spec.SetField(discordmessage.FieldEditedTimestamp, field.TypeTime, value)
		_node.EditedTimestamp = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discordmessage.UserTable,
			Columns: []string{discordmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiscordMessageCreateBulk is the builder for creating many DiscordMessage entities in bulk.
type DiscordMessageCreateBulk struct {
	config
	err      error
	builders []*DiscordMessageCreate
}

// Save creates the DiscordMessage entities in the database.
func (_c *DiscordMessageCreateBulk) Save(ctx context.Context) ([]*DiscordMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordMessageCreateBulk) SaveX(ctx context.Context) []*DiscordMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
