// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DiscordMessage is the model entity for the DiscordMessage schema.
type DiscordMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// AuthorID holds the value of the "author_id" field.
	AuthorID string `json:"author_id,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// EditedTimestamp holds the value of the "edited_timestamp" field.
	EditedTimestamp time.Time `json:"edited_timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiscordMessageQuery when eager-loading is set.
	Edges        DiscordMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DiscordMessageEdges holds the relations/edges for other nodes in the graph.
type DiscordMessageEdges struct {
	// User holds the value of the user edge.
	User *DiscordUser `json:"user,omitempty"`
	// Embeddings holds the value of the embeddings edge.
	Embeddings []*DiscordMessageEmbedding `json:"embeddings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DiscordMessageEdges) UserOrErr() (*DiscordUser, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: discorduser.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// EmbeddingsOrErr returns the Embeddings value or an error if the edge
// was not loaded in eager-loading.
func (e DiscordMessageEdges) EmbeddingsOrErr() ([]*DiscordMessageEmbedding, error) {
	if e.loadedTypes[1] {
		return e.Embeddings, nil
	}
	return nil, &NotLoadedError{edge: "embeddings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscordMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discordmessage.FieldID, discordmessage.FieldContent, discordmessage.FieldAuthorID:
			values[i] = new(sql.NullString)
		case discordmessage.FieldTimestamp, discordmessage.FieldEditedTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscordMessage fields.
func (_m *DiscordMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discordmessage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case discordmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case discordmessage.FieldAuthorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value.Valid {
				_m.AuthorID = value.String
			}
		case discordmessage.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case discordmessage.FieldEditedTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field edited_timestamp", values[i])
			} else if value.Valid {
				_m.EditedTimestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscordMessage.
// This includes values selected through modifiers, order, etc.
func (_m *DiscordMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the DiscordMessage entity.
func (_m *DiscordMessage) QueryUser() *DiscordUserQuery {
	return NewDiscordMessageClient(_m.config).QueryUser(_m)
}

// QueryEmbeddings queries the "embeddings" edge of the DiscordMessage entity.
func (_m *DiscordMessage) QueryEmbeddings() *DiscordMessageEmbeddingQuery {
	return NewDiscordMessageClient(_m.config).QueryEmbeddings(_m)
}

// Update returns a builder for updating this DiscordMessage.
// Note that you need to call DiscordMessage.Unwrap() before calling this method if this DiscordMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscordMessage) Update() *DiscordMessageUpdateOne {
	return NewDiscordMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscordMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscordMessage) Unwrap() *DiscordMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscordMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscordMessage) String() string {
	var builder strings.Builder
	builder.WriteString("DiscordMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(_m.AuthorID)
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("edited_timestamp=")
	builder.WriteString(_m.EditedTimestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DiscordMessages is a parsable slice of DiscordMessage.
type DiscordMessages []*DiscordMessage
