// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordUserCreate is the builder for creating a DiscordUser entity.
type DiscordUserCreate struct {
	config
	mutation *DiscordUserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *DiscordUserCreate) SetUsername(v string) *DiscordUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetGlobalName sets the "global_name" field.
func (_c *DiscordUserCreate) SetGlobalName(v string) *DiscordUserCreate {
	_c.mutation.SetGlobalName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DiscordUserCreate) SetID(v string) *DiscordUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMessageIDs adds the "messages" edge to the DiscordMessage entity by IDs.
func (_c *DiscordUserCreate) AddMessageIDs(ids ...string) *DiscordUserCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the DiscordMessage entity.
func (_c *DiscordUserCreate) AddMessages(v ...*DiscordMessage) *DiscordUserCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the DiscordUserMutation object of the builder.
func (_c *DiscordUserCreate) Mutation() *DiscordUserMutation {
	return _c.mutation
}

// Save creates the DiscordUser in the database.
func (_c *DiscordUserCreate) Save(ctx context.Context) (*DiscordUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordUserCreate) SaveX(ctx context.Context) *DiscordUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordUserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "DiscordUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := discorduser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GlobalName(); !ok {
		return &ValidationError{Name: "global_name", err: errors.New(`ent: missing required field "DiscordUser.global_name"`)}
	}
	if v, ok := _c.mutation.GlobalName(); ok {
		if err := discorduser.GlobalNameValidator(v); err != nil {
			return &ValidationError{Name: "global_name", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.global_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := discorduser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DiscordUserCreate) sqlSave(ctx context.Context) (*DiscordUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DiscordUser.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordUserCreate) createSpec() (*DiscordUser, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discorduser.Table, sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(discorduser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.GlobalName(); ok {
		_spec.SetField(discorduser.FieldGlobalName, field.TypeString, value)
		_node.GlobalName = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiscordUserCreateBulk is the builder for creating many DiscordUser entities in bulk.
type DiscordUserCreateBulk struct {
	config
	err      error
	builders []*DiscordUserCreate
}

// Save creates the DiscordUser entities in the database.
func (_c *DiscordUserCreateBulk) Save(ctx context.Context) ([]*DiscordUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordUserCreateBulk) SaveX(ctx context.Context) []*DiscordUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
