// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sev0/ent/discorduser"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DiscordUser is the model entity for the DiscordUser schema.
type DiscordUser struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// GlobalName holds the value of the "global_name" field.
	GlobalName string `json:"global_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiscordUserQuery when eager-loading is set.
	Edges        DiscordUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DiscordUserEdges holds the relations/edges for other nodes in the graph.
type DiscordUserEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*DiscordMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e DiscordUserEdges) MessagesOrErr() ([]*DiscordMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscordUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discorduser.FieldID, discorduser.FieldUsername, discorduser.FieldGlobalName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscordUser fields.
func (_m *DiscordUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discorduser.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case discorduser.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case discorduser.FieldGlobalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field global_name", values[i])
			} else if value.Valid {
				_m.GlobalName = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscordUser.
// This includes values selected through modifiers, order, etc.
func (_m *DiscordUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the DiscordUser entity.
func (_m *DiscordUser) QueryMessages() *DiscordMessageQuery {
	return NewDiscordUserClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this DiscordUser.
// Note that you need to call DiscordUser.Unwrap() before calling this method if this DiscordUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscordUser) Update() *DiscordUserUpdateOne {
	return NewDiscordUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscordUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscordUser) Unwrap() *DiscordUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscordUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscordUser) String() string {
	var builder strings.Builder
	builder.WriteString("DiscordUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("global_name=")
	builder.WriteString(_m.GlobalName)
	builder.WriteByte(')')
	return builder.String()
}

// DiscordUsers is a parsable slice of DiscordUser.
type DiscordUsers []*DiscordUser
