// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discordmessageembedding"
	"sev0/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordMessageUpdate is the builder for updating DiscordMessage entities.
type DiscordMessageUpdate struct {
	config
	hooks    []Hook
	mutation *DiscordMessageMutation
}

// Where appends a list predicates to the DiscordMessageUpdate builder.
func (_u *DiscordMessageUpdate) Where(ps ...predicate.DiscordMessage) *DiscordMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *DiscordMessageUpdate) SetContent(v string) *DiscordMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DiscordMessageUpdate) SetNillableContent(v *string) *DiscordMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (_u *DiscordMessageUpdate) SetEditedTimestamp(v time.Time) *DiscordMessageUpdate {
	_u.mutation.SetEditedTimestamp(v)
	return _u
}

// SetNillableEditedTimestamp sets the "edited_timestamp" field if the given value is not nil.
func (_u *DiscordMessageUpdate) SetNillableEditedTimestamp(v *time.Time) *DiscordMessageUpdate {
	if v != nil {
		_u.SetEditedTimestamp(*v)
	}
	return _u
}

// ClearEditedTimestamp clears the value of the "edited_timestamp" field.
func (_u *DiscordMessageUpdate) ClearEditedTimestamp() *DiscordMessageUpdate {
	_u.mutation.ClearEditedTimestamp()
	return _u
}

// AddEmbeddingIDs adds the "embeddings" edge to the DiscordMessageEmbedding entity by IDs.
func (_u *DiscordMessageUpdate) AddEmbeddingIDs(ids ...string) *DiscordMessageUpdate {
	_u.mutation.AddEmbeddingIDs(ids...)
	return _u
}

// AddEmbeddings adds the "embeddings" edges to the DiscordMessageEmbedding entity.
func (_u *DiscordMessageUpdate) AddEmbeddings(v ...*DiscordMessageEmbedding) *DiscordMessageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmbeddingIDs(ids...)
}

// Mutation returns the DiscordMessageMutation object of the builder.
func (_u *DiscordMessageUpdate) Mutation() *DiscordMessageMutation {
	return _u.mutation
}

// ClearEmbeddings clears all "embeddings" edges to the DiscordMessageEmbedding entity.
func (_u *DiscordMessageUpdate) ClearEmbeddings() *DiscordMessageUpdate {
	_u.mutation.ClearEmbeddings()
	return _u
}

// RemoveEmbeddingIDs removes the "embeddings" edge to DiscordMessageEmbedding entities by IDs.
func (_u *DiscordMessageUpdate) RemoveEmbeddingIDs(ids ...string) *DiscordMessageUpdate {
	_u.mutation.RemoveEmbeddingIDs(ids...)
	return _u
}

// RemoveEmbeddings removes "embeddings" edges to DiscordMessageEmbedding entities.
func (_u *DiscordMessageUpdate) RemoveEmbeddings(v ...*DiscordMessageEmbedding) *DiscordMessageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmbeddingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscordMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscordMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordMessageUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiscordMessage.user"`)
	}
	return nil
}

func (_u *DiscordMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordmessage.Table, discordmessage.Columns, sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(discordmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditedTimestamp(); ok {
		_spec.SetField(discordmessage.FieldEditedTimestamp, field.TypeTime, value)
	}
	if _u.mutation.EditedTimestampCleared() {
		_spec.ClearField(discordmessage.FieldEditedTimestamp, field.TypeTime)
	}
	if _u.mutation.EmbeddingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordmessage.EmbeddingsTable,
			Columns: []string{discordmessage.EmbeddingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmbeddingsIDs(); len(nodes) > 0 && !_u.mutation.EmbeddingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordmessage.EmbeddingsTable,
			Columns: []string{discordmessage.EmbeddingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmbeddingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordmessage.EmbeddingsTable,
			Columns: []string{discordmessage.EmbeddingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscordMessageUpdateOne is the builder for updating a single DiscordMessage entity.
type DiscordMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscordMessageMutation
}

// SetContent sets the "content" field.
func (_u *DiscordMessageUpdateOne) SetContent(v string) *DiscordMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DiscordMessageUpdateOne) SetNillableContent(v *string) *DiscordMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (_u *DiscordMessageUpdateOne) SetEditedTimestamp(v time.Time) *DiscordMessageUpdateOne {
	_u.mutation.SetEditedTimestamp(v)
	return _u
}

// SetNillableEditedTimestamp sets the "edited_timestamp" field if the given value is not nil.
func (_u *DiscordMessageUpdateOne) SetNillableEditedTimestamp(v *time.Time) *DiscordMessageUpdateOne {
	if v != nil {
		_u.SetEditedTimestamp(*v)
	}
	return _u
}

// ClearEditedTimestamp clears the value of the "edited_timestamp" field.
func (_u *DiscordMessageUpdateOne) ClearEditedTimestamp() *DiscordMessageUpdateOne {
	_u.mutation.ClearEditedTimestamp()
	return _u
}

// AddEmbeddingIDs adds the "embeddings" edge to the DiscordMessageEmbedding entity by IDs.
func (_u *DiscordMessageUpdateOne) AddEmbeddingIDs(ids ...string) *DiscordMessageUpdateOne {
	_u.mutation.AddEmbeddingIDs(ids...)
	return _u
}

// AddEmbeddings adds the "embeddings" edges to the DiscordMessageEmbedding entity.
func (_u *DiscordMessageUpdateOne) AddEmbeddings(v ...*DiscordMessageEmbedding) *DiscordMessageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmbeddingIDs(ids...)
}

// Mutation returns the DiscordMessageMutation object of the builder.
func (_u *DiscordMessageUpdateOne) Mutation() *DiscordMessageMutation {
	return _u.mutation
}

// ClearEmbeddings clears all "embeddings" edges to the DiscordMessageEmbedding entity.
func (_u *DiscordMessageUpdateOne) ClearEmbeddings() *DiscordMessageUpdateOne {
	_u.mutation.ClearEmbeddings()
	return _u
}

// RemoveEmbeddingIDs removes the "embeddings" edge to DiscordMessageEmbedding entities by IDs.
func (_u *DiscordMessageUpdateOne) RemoveEmbeddingIDs(ids ...string) *DiscordMessageUpdateOne {
	_u.mutation.RemoveEmbeddingIDs(ids...)
	return _u
}

// RemoveEmbeddings removes "embeddings" edges to DiscordMessageEmbedding entities.
func (_u *DiscordMessageUpdateOne) RemoveEmbeddings(v ...*DiscordMessageEmbedding) *DiscordMessageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmbeddingIDs(ids...)
}

// Where appends a list predicates to the DiscordMessageUpdate builder.
func (_u *DiscordMessageUpdateOne) Where(ps ...predicate.DiscordMessage) *DiscordMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscordMessageUpdateOne) Select(field string, fields ...string) *DiscordMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscordMessage entity.
func (_u *DiscordMessageUpdateOne) Save(ctx context.Context) (*DiscordMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordMessageUpdateOne) SaveX(ctx context.Context) *DiscordMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscordMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordMessageUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiscordMessage.user"`)
	}
	return nil
}

func (_u *DiscordMessageUpdateOne) sqlSave(ctx context.Context) (_node *DiscordMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordmessage.Table, discordmessage.Columns, sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscordMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordmessage.FieldID)
		for _, f := range fields {
			if !discordmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discordmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(discordmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditedTimestamp(); ok {
		_spec.SetField(discordmessage.FieldEditedTimestamp, field.TypeTime, value)
	}
	if _u.mutation.EditedTimestampCleared() {
		_spec.ClearField(discordmessage.FieldEditedTimestamp, field.TypeTime)
	}
	if _u.mutation.EmbeddingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordmessage.EmbeddingsTable,
			Columns: []string{discordmessage.EmbeddingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmbeddingsIDs(); len(nodes) > 0 && !_u.mutation.EmbeddingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordmessage.EmbeddingsTable,
			Columns: []string{discordmessage.EmbeddingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmbeddingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discordmessage.EmbeddingsTable,
			Columns: []string{discordmessage.EmbeddingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DiscordMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
