// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordUserCreate is the builder for creating a DiscordUser entity.
type DiscordUserCreate struct {
	config
	mutation *DiscordUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsername sets the "username" field.
func (_c *DiscordUserCreate) SetUsername(v string) *DiscordUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetGlobalName sets the "global_name" field.
func (_c *DiscordUserCreate) SetGlobalName(v string) *DiscordUserCreate {
	_c.mutation.SetGlobalName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DiscordUserCreate) SetID(v string) *DiscordUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMessageIDs adds the "messages" edge to the DiscordMessage entity by IDs.
func (_c *DiscordUserCreate) AddMessageIDs(ids ...string) *DiscordUserCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the DiscordMessage entity.
func (_c *DiscordUserCreate) AddMessages(v ...*DiscordMessage) *DiscordUserCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the DiscordUserMutation object of the builder.
func (_c *DiscordUserCreate) Mutation() *DiscordUserMutation {
	return _c.mutation
}

// Save creates the DiscordUser in the database.
func (_c *DiscordUserCreate) Save(ctx context.Context) (*DiscordUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscordUserCreate) SaveX(ctx context.Context) *DiscordUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscordUserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "DiscordUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := discorduser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GlobalName(); !ok {
		return &ValidationError{Name: "global_name", err: errors.New(`ent: missing required field "DiscordUser.global_name"`)}
	}
	if v, ok := _c.mutation.GlobalName(); ok {
		if err := discorduser.GlobalNameValidator(v); err != nil {
			return &ValidationError{Name: "global_name", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.global_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := discorduser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DiscordUserCreate) sqlSave(ctx context.Context) (*DiscordUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DiscordUser.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscordUserCreate) createSpec() (*DiscordUser, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discorduser.Table, sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(discorduser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.GlobalName(); ok {
		_spec.SetField(discorduser.FieldGlobalName, field.TypeString, value)
		_node.GlobalName = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordUser.Create().
//		SetUsername(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordUserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordUserCreate) OnConflict(opts ...sql.ConflictOption) *DiscordUserUpsertOne {
	_c.conflict = opts
	return &DiscordUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordUserCreate) OnConflictColumns(columns ...string) *DiscordUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordUserUpsertOne{
		create: _c,
	}
}

type (
	// DiscordUserUpsertOne is the builder for "upsert"-ing
	//  one DiscordUser node.
	DiscordUserUpsertOne struct {
		create *DiscordUserCreate
	}

	// DiscordUserUpsert is the "OnConflict" setter.
	DiscordUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsername sets the "username" field.
func (u *DiscordUserUpsert) SetUsername(v string) *DiscordUserUpsert {
	u.Set(discorduser.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *DiscordUserUpsert) UpdateUsername() *DiscordUserUpsert {
	u.SetExcluded(discorduser.FieldUsername)
	return u
}

// SetGlobalName sets the "global_name" field.
func (u *DiscordUserUpsert) SetGlobalName(v string) *DiscordUserUpsert {
	u.Set(discorduser.FieldGlobalName, v)
	return u
}

// UpdateGlobalName sets the "global_name" field to the value that was provided on create.
func (u *DiscordUserUpsert) UpdateGlobalName() *DiscordUserUpsert {
	u.SetExcluded(discorduser.FieldGlobalName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DiscordUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(discorduser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiscordUserUpsertOne) UpdateNewValues() *DiscordUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(discorduser.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DiscordUserUpsertOne) Ignore() *DiscordUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordUserUpsertOne) DoNothing() *DiscordUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordUserCreate.OnConflict
// documentation for more info.
func (u *DiscordUserUpsertOne) Update(set func(*DiscordUserUpsert)) *DiscordUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *DiscordUserUpsertOne) SetUsername(v string) *DiscordUserUpsertOne {
	return u.Update(func(s *DiscordUserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *DiscordUserUpsertOne) UpdateUsername() *DiscordUserUpsertOne {
	return u.Update(func(s *DiscordUserUpsert) {
		s.UpdateUsername()
	})
}

// SetGlobalName sets the "global_name" field.
func (u *DiscordUserUpsertOne) SetGlobalName(v string) *DiscordUserUpsertOne {
	return u.Update(func(s *DiscordUserUpsert) {
		s.SetGlobalName(v)
	})
}

// UpdateGlobalName sets the "global_name" field to the value that was provided on create.
func (u *DiscordUserUpsertOne) UpdateGlobalName() *DiscordUserUpsertOne {
	return u.Update(func(s *DiscordUserUpsert) {
		s.UpdateGlobalName()
	})
}

// Exec executes the query.
func (u *DiscordUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DiscordUserUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DiscordUserUpsertOne.ID is not supported by MySQL driver. Use DiscordUserUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DiscordUserUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DiscordUserCreateBulk is the builder for creating many DiscordUser entities in bulk.
type DiscordUserCreateBulk struct {
	config
	err      error
	builders []*DiscordUserCreate
	conflict []sql.ConflictOption
}

// Save creates the DiscordUser entities in the database.
func (_c *DiscordUserCreateBulk) Save(ctx context.Context) ([]*DiscordUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscordUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscordUserCreateBulk) SaveX(ctx context.Context) []*DiscordUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscordUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscordUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DiscordUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DiscordUserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *DiscordUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *DiscordUserUpsertBulk {
	_c.conflict = opts
	return &DiscordUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DiscordUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DiscordUserCreateBulk) OnConflictColumns(columns ...string) *DiscordUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DiscordUserUpsertBulk{
		create: _c,
	}
}

// DiscordUserUpsertBulk is the builder for "upsert"-ing
// a bulk of DiscordUser nodes.
type DiscordUserUpsertBulk struct {
	create *DiscordUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DiscordUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(discorduser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DiscordUserUpsertBulk) UpdateNewValues() *DiscordUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(discorduser.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DiscordUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DiscordUserUpsertBulk) Ignore() *DiscordUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DiscordUserUpsertBulk) DoNothing() *DiscordUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DiscordUserCreateBulk.OnConflict
// documentation for more info.
func (u *DiscordUserUpsertBulk) Update(set func(*DiscordUserUpsert)) *DiscordUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DiscordUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *DiscordUserUpsertBulk) SetUsername(v string) *DiscordUserUpsertBulk {
	return u.Update(func(s *DiscordUserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *DiscordUserUpsertBulk) UpdateUsername() *DiscordUserUpsertBulk {
	return u.Update(func(s *DiscordUserUpsert) {
		s.UpdateUsername()
	})
}

// SetGlobalName sets the "global_name" field.
func (u *DiscordUserUpsertBulk) SetGlobalName(v string) *DiscordUserUpsertBulk {
	return u.Update(func(s *DiscordUserUpsert) {
		s.SetGlobalName(v)
	})
}

// UpdateGlobalName sets the "global_name" field to the value that was provided on create.
func (u *DiscordUserUpsertBulk) UpdateGlobalName() *DiscordUserUpsertBulk {
	return u.Update(func(s *DiscordUserUpsert) {
		s.UpdateGlobalName()
	})
}

// Exec executes the query.
func (u *DiscordUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DiscordUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DiscordUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DiscordUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
