// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessageembedding"
	"sev0/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	pgvector "github.com/pgvector/pgvector-go"
)

// DiscordMessageEmbeddingUpdate is the builder for updating DiscordMessageEmbedding entities.
type DiscordMessageEmbeddingUpdate struct {
	config
	hooks    []Hook
	mutation *DiscordMessageEmbeddingMutation
}

// Where appends a list predicates to the DiscordMessageEmbeddingUpdate builder.
func (_u *DiscordMessageEmbeddingUpdate) Where(ps ...predicate.DiscordMessageEmbedding) *DiscordMessageEmbeddingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *DiscordMessageEmbeddingUpdate) SetEmbedding(v pgvector.Vector) *DiscordMessageEmbeddingUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *DiscordMessageEmbeddingUpdate) SetNillableEmbedding(v *pgvector.Vector) *DiscordMessageEmbeddingUpdate {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// Mutation returns the DiscordMessageEmbeddingMutation object of the builder.
func (_u *DiscordMessageEmbeddingUpdate) Mutation() *DiscordMessageEmbeddingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscordMessageEmbeddingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordMessageEmbeddingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscordMessageEmbeddingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordMessageEmbeddingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordMessageEmbeddingUpdate) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiscordMessageEmbedding.message"`)
	}
	return nil
}

func (_u *DiscordMessageEmbeddingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordmessageembedding.Table, discordmessageembedding.Columns, sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(discordmessageembedding.FieldEmbedding, field.TypeOther, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordmessageembedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscordMessageEmbeddingUpdateOne is the builder for updating a single DiscordMessageEmbedding entity.
type DiscordMessageEmbeddingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscordMessageEmbeddingMutation
}

// SetEmbedding sets the "embedding" field.
func (_u *DiscordMessageEmbeddingUpdateOne) SetEmbedding(v pgvector.Vector) *DiscordMessageEmbeddingUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *DiscordMessageEmbeddingUpdateOne) SetNillableEmbedding(v *pgvector.Vector) *DiscordMessageEmbeddingUpdateOne {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// Mutation returns the DiscordMessageEmbeddingMutation object of the builder.
func (_u *DiscordMessageEmbeddingUpdateOne) Mutation() *DiscordMessageEmbeddingMutation {
	return _u.mutation
}

// Where appends a list predicates to the DiscordMessageEmbeddingUpdate builder.
func (_u *DiscordMessageEmbeddingUpdateOne) Where(ps ...predicate.DiscordMessageEmbedding) *DiscordMessageEmbeddingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscordMessageEmbeddingUpdateOne) Select(field string, fields ...string) *DiscordMessageEmbeddingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscordMessageEmbedding entity.
func (_u *DiscordMessageEmbeddingUpdateOne) Save(ctx context.Context) (*DiscordMessageEmbedding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordMessageEmbeddingUpdateOne) SaveX(ctx context.Context) *DiscordMessageEmbedding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscordMessageEmbeddingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordMessageEmbeddingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordMessageEmbeddingUpdateOne) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiscordMessageEmbedding.message"`)
	}
	return nil
}

func (_u *DiscordMessageEmbeddingUpdateOne) sqlSave(ctx context.Context) (_node *DiscordMessageEmbedding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordmessageembedding.Table, discordmessageembedding.Columns, sqlgraph.NewFieldSpec(discordmessageembedding.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscordMessageEmbedding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordmessageembedding.FieldID)
		for _, f := range fields {
			if !discordmessageembedding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discordmessageembedding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(discordmessageembedding.FieldEmbedding, field.TypeOther, value)
	}
	_node = &DiscordMessageEmbedding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordmessageembedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
