// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"
	"sev0/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordUserUpdate is the builder for updating DiscordUser entities.
type DiscordUserUpdate struct {
	config
	hooks    []Hook
	mutation *DiscordUserMutation
}

// Where appends a list predicates to the DiscordUserUpdate builder.
func (_u *DiscordUserUpdate) Where(ps ...predicate.DiscordUser) *DiscordUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *DiscordUserUpdate) SetUsername(v string) *DiscordUserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *DiscordUserUpdate) SetNillableUsername(v *string) *DiscordUserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetGlobalName sets the "global_name" field.
func (_u *DiscordUserUpdate) SetGlobalName(v string) *DiscordUserUpdate {
	_u.mutation.SetGlobalName(v)
	return _u
}

// SetNillableGlobalName sets the "global_name" field if the given value is not nil.
func (_u *DiscordUserUpdate) SetNillableGlobalName(v *string) *DiscordUserUpdate {
	if v != nil {
		_u.SetGlobalName(*v)
	}
	return _u
}

// AddMessageIDs adds the "messages" edge to the DiscordMessage entity by IDs.
func (_u *DiscordUserUpdate) AddMessageIDs(ids ...string) *DiscordUserUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the DiscordMessage entity.
func (_u *DiscordUserUpdate) AddMessages(v ...*DiscordMessage) *DiscordUserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the DiscordUserMutation object of the builder.
func (_u *DiscordUserUpdate) Mutation() *DiscordUserMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the DiscordMessage entity.
func (_u *DiscordUserUpdate) ClearMessages() *DiscordUserUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to DiscordMessage entities by IDs.
func (_u *DiscordUserUpdate) RemoveMessageIDs(ids ...string) *DiscordUserUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to DiscordMessage entities.
func (_u *DiscordUserUpdate) RemoveMessages(v ...*DiscordMessage) *DiscordUserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscordUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscordUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordUserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := discorduser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GlobalName(); ok {
		if err := discorduser.GlobalNameValidator(v); err != nil {
			return &ValidationError{Name: "global_name", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.global_name": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscordUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discorduser.Table, discorduser.Columns, sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(discorduser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.GlobalName(); ok {
		_spec.SetField(discorduser.FieldGlobalName, field.TypeString, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discorduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscordUserUpdateOne is the builder for updating a single DiscordUser entity.
type DiscordUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscordUserMutation
}

// SetUsername sets the "username" field.
func (_u *DiscordUserUpdateOne) SetUsername(v string) *DiscordUserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *DiscordUserUpdateOne) SetNillableUsername(v *string) *DiscordUserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetGlobalName sets the "global_name" field.
func (_u *DiscordUserUpdateOne) SetGlobalName(v string) *DiscordUserUpdateOne {
	_u.mutation.SetGlobalName(v)
	return _u
}

// SetNillableGlobalName sets the "global_name" field if the given value is not nil.
func (_u *DiscordUserUpdateOne) SetNillableGlobalName(v *string) *DiscordUserUpdateOne {
	if v != nil {
		_u.SetGlobalName(*v)
	}
	return _u
}

// AddMessageIDs adds the "messages" edge to the DiscordMessage entity by IDs.
func (_u *DiscordUserUpdateOne) AddMessageIDs(ids ...string) *DiscordUserUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the DiscordMessage entity.
func (_u *DiscordUserUpdateOne) AddMessages(v ...*DiscordMessage) *DiscordUserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the DiscordUserMutation object of the builder.
func (_u *DiscordUserUpdateOne) Mutation() *DiscordUserMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the DiscordMessage entity.
func (_u *DiscordUserUpdateOne) ClearMessages() *DiscordUserUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to DiscordMessage entities by IDs.
func (_u *DiscordUserUpdateOne) RemoveMessageIDs(ids ...string) *DiscordUserUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to DiscordMessage entities.
func (_u *DiscordUserUpdateOne) RemoveMessages(v ...*DiscordMessage) *DiscordUserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the DiscordUserUpdate builder.
func (_u *DiscordUserUpdateOne) Where(ps ...predicate.DiscordUser) *DiscordUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscordUserUpdateOne) Select(field string, fields ...string) *DiscordUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscordUser entity.
func (_u *DiscordUserUpdateOne) Save(ctx context.Context) (*DiscordUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordUserUpdateOne) SaveX(ctx context.Context) *DiscordUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscordUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordUserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := discorduser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GlobalName(); ok {
		if err := discorduser.GlobalNameValidator(v); err != nil {
			return &ValidationError{Name: "global_name", err: fmt.Errorf(`ent: validator failed for field "DiscordUser.global_name": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscordUserUpdateOne) sqlSave(ctx context.Context) (_node *DiscordUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discorduser.Table, discorduser.Columns, sqlgraph.NewFieldSpec(discorduser.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscordUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discorduser.FieldID)
		for _, f := range fields {
			if !discorduser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discorduser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(discorduser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.GlobalName(); ok {
		_spec.SetField(discorduser.FieldGlobalName, field.TypeString, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.MessagesTable,
			Columns: []string{discorduser.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discordmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DiscordUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discorduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
