// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sev0/ent/discordmessage"
	"sev0/ent/discorduser"
	"sev0/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDiscordMessage = "DiscordMessage"
	TypeDiscordUser    = "DiscordUser"
)

// DiscordMessageMutation represents an operation that mutates the DiscordMessage nodes in the graph.
type DiscordMessageMutation struct {
	config
	op               Op
	typ              string
	id               *string
	content          *string
	timestamp        *time.Time
	edited_timestamp *time.Time
	clearedFields    map[string]struct{}
	user             *string
	cleareduser      bool
	done             bool
	oldValue         func(context.Context) (*DiscordMessage, error)
	predicates       []predicate.DiscordMessage
}

var _ ent.Mutation = (*DiscordMessageMutation)(nil)

// discordmessageOption allows management of the mutation configuration using functional options.
type discordmessageOption func(*DiscordMessageMutation)

// newDiscordMessageMutation creates new mutation for the DiscordMessage entity.
func newDiscordMessageMutation(c config, op Op, opts ...discordmessageOption) *DiscordMessageMutation {
	m := &DiscordMessageMutation{
		config:        c,
		op:            op,
		typ:           TypeDiscordMessage,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDiscordMessageID sets the ID field of the mutation.
func withDiscordMessageID(id string) discordmessageOption {
	return func(m *DiscordMessageMutation) {
		var (
			err   error
			once  sync.Once
			value *DiscordMessage
		)
		m.oldValue = func(ctx context.Context) (*DiscordMessage, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DiscordMessage.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDiscordMessage sets the old DiscordMessage of the mutation.
func withDiscordMessage(node *DiscordMessage) discordmessageOption {
	return func(m *DiscordMessageMutation) {
		m.oldValue = func(context.Context) (*DiscordMessage, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DiscordMessageMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DiscordMessageMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DiscordMessage entities.
func (m *DiscordMessageMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DiscordMessageMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DiscordMessageMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DiscordMessage.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetContent sets the "content" field.
func (m *DiscordMessageMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *DiscordMessageMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the DiscordMessage entity.
// If the DiscordMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiscordMessageMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *DiscordMessageMutation) ResetContent() {
	m.content = nil
}

// SetAuthorID sets the "author_id" field.
func (m *DiscordMessageMutation) SetAuthorID(s string) {
	m.user = &s
}

// AuthorID returns the value of the "author_id" field in the mutation.
func (m *DiscordMessageMutation) AuthorID() (r string, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldAuthorID returns the old "author_id" field's value of the DiscordMessage entity.
// If the DiscordMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiscordMessageMutation) OldAuthorID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuthorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuthorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuthorID: %w", err)
	}
	return oldValue.AuthorID, nil
}

// ResetAuthorID resets all changes to the "author_id" field.
func (m *DiscordMessageMutation) ResetAuthorID() {
	m.user = nil
}

// SetTimestamp sets the "timestamp" field.
func (m *DiscordMessageMutation) SetTimestamp(t time.Time) {
	m.timestamp = &t
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *DiscordMessageMutation) Timestamp() (r time.Time, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the DiscordMessage entity.
// If the DiscordMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiscordMessageMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *DiscordMessageMutation) ResetTimestamp() {
	m.timestamp = nil
}

// SetEditedTimestamp sets the "edited_timestamp" field.
func (m *DiscordMessageMutation) SetEditedTimestamp(t time.Time) {
	m.edited_timestamp = &t
}

// EditedTimestamp returns the value of the "edited_timestamp" field in the mutation.
func (m *DiscordMessageMutation) EditedTimestamp() (r time.Time, exists bool) {
	v := m.edited_timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldEditedTimestamp returns the old "edited_timestamp" field's value of the DiscordMessage entity.
// If the DiscordMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiscordMessageMutation) OldEditedTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEditedTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEditedTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEditedTimestamp: %w", err)
	}
	return oldValue.EditedTimestamp, nil
}

// ResetEditedTimestamp resets all changes to the "edited_timestamp" field.
func (m *DiscordMessageMutation) ResetEditedTimestamp() {
	m.edited_timestamp = nil
}

// SetUserID sets the "user" edge to the DiscordUser entity by id.
func (m *DiscordMessageMutation) SetUserID(id string) {
	m.user = &id
}

// ClearUser clears the "user" edge to the DiscordUser entity.
func (m *DiscordMessageMutation) ClearUser() {
	m.cleareduser = true
	m.clearedFields[discordmessage.FieldAuthorID] = struct{}{}
}

// UserCleared reports if the "user" edge to the DiscordUser entity was cleared.
func (m *DiscordMessageMutation) UserCleared() bool {
	return m.cleareduser
}

// UserID returns the "user" edge ID in the mutation.
func (m *DiscordMessageMutation) UserID() (id string, exists bool) {
	if m.user != nil {
		return *m.user, true
	}
	return
}

// UserIDs returns the "user" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UserID instead. It exists only for internal usage by the builders.
func (m *DiscordMessageMutation) UserIDs() (ids []string) {
	if id := m.user; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUser resets all changes to the "user" edge.
func (m *DiscordMessageMutation) ResetUser() {
	m.user = nil
	m.cleareduser = false
}

// Where appends a list predicates to the DiscordMessageMutation builder.
func (m *DiscordMessageMutation) Where(ps ...predicate.DiscordMessage) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DiscordMessageMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DiscordMessageMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DiscordMessage, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DiscordMessageMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DiscordMessageMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DiscordMessage).
func (m *DiscordMessageMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DiscordMessageMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.content != nil {
		fields = append(fields, discordmessage.FieldContent)
	}
	if m.user != nil {
		fields = append(fields, discordmessage.FieldAuthorID)
	}
	if m.timestamp != nil {
		fields = append(fields, discordmessage.FieldTimestamp)
	}
	if m.edited_timestamp != nil {
		fields = append(fields, discordmessage.FieldEditedTimestamp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DiscordMessageMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case discordmessage.FieldContent:
		return m.Content()
	case discordmessage.FieldAuthorID:
		return m.AuthorID()
	case discordmessage.FieldTimestamp:
		return m.Timestamp()
	case discordmessage.FieldEditedTimestamp:
		return m.EditedTimestamp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DiscordMessageMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case discordmessage.FieldContent:
		return m.OldContent(ctx)
	case discordmessage.FieldAuthorID:
		return m.OldAuthorID(ctx)
	case discordmessage.FieldTimestamp:
		return m.OldTimestamp(ctx)
	case discordmessage.FieldEditedTimestamp:
		return m.OldEditedTimestamp(ctx)
	}
	return nil, fmt.Errorf("unknown DiscordMessage field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DiscordMessageMutation) SetField(name string, value ent.Value) error {
	switch name {
	case discordmessage.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case discordmessage.FieldAuthorID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthorID(v)
		return nil
	case discordmessage.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	case discordmessage.FieldEditedTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEditedTimestamp(v)
		return nil
	}
	return fmt.Errorf("unknown DiscordMessage field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DiscordMessageMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DiscordMessageMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DiscordMessageMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DiscordMessage numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DiscordMessageMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DiscordMessageMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DiscordMessageMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DiscordMessage nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DiscordMessageMutation) ResetField(name string) error {
	switch name {
	case discordmessage.FieldContent:
		m.ResetContent()
		return nil
	case discordmessage.FieldAuthorID:
		m.ResetAuthorID()
		return nil
	case discordmessage.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	case discordmessage.FieldEditedTimestamp:
		m.ResetEditedTimestamp()
		return nil
	}
	return fmt.Errorf("unknown DiscordMessage field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DiscordMessageMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.user != nil {
		edges = append(edges, discordmessage.EdgeUser)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DiscordMessageMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case discordmessage.EdgeUser:
		if id := m.user; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DiscordMessageMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DiscordMessageMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DiscordMessageMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleareduser {
		edges = append(edges, discordmessage.EdgeUser)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DiscordMessageMutation) EdgeCleared(name string) bool {
	switch name {
	case discordmessage.EdgeUser:
		return m.cleareduser
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DiscordMessageMutation) ClearEdge(name string) error {
	switch name {
	case discordmessage.EdgeUser:
		m.ClearUser()
		return nil
	}
	return fmt.Errorf("unknown DiscordMessage unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DiscordMessageMutation) ResetEdge(name string) error {
	switch name {
	case discordmessage.EdgeUser:
		m.ResetUser()
		return nil
	}
	return fmt.Errorf("unknown DiscordMessage edge %s", name)
}

// DiscordUserMutation represents an operation that mutates the DiscordUser nodes in the graph.
type DiscordUserMutation struct {
	config
	op              Op
	typ             string
	id              *string
	username        *string
	global_name     *string
	clearedFields   map[string]struct{}
	messages        map[string]struct{}
	removedmessages map[string]struct{}
	clearedmessages bool
	done            bool
	oldValue        func(context.Context) (*DiscordUser, error)
	predicates      []predicate.DiscordUser
}

var _ ent.Mutation = (*DiscordUserMutation)(nil)

// discorduserOption allows management of the mutation configuration using functional options.
type discorduserOption func(*DiscordUserMutation)

// newDiscordUserMutation creates new mutation for the DiscordUser entity.
func newDiscordUserMutation(c config, op Op, opts ...discorduserOption) *DiscordUserMutation {
	m := &DiscordUserMutation{
		config:        c,
		op:            op,
		typ:           TypeDiscordUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDiscordUserID sets the ID field of the mutation.
func withDiscordUserID(id string) discorduserOption {
	return func(m *DiscordUserMutation) {
		var (
			err   error
			once  sync.Once
			value *DiscordUser
		)
		m.oldValue = func(ctx context.Context) (*DiscordUser, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DiscordUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDiscordUser sets the old DiscordUser of the mutation.
func withDiscordUser(node *DiscordUser) discorduserOption {
	return func(m *DiscordUserMutation) {
		m.oldValue = func(context.Context) (*DiscordUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DiscordUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DiscordUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DiscordUser entities.
func (m *DiscordUserMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DiscordUserMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DiscordUserMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DiscordUser.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *DiscordUserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *DiscordUserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the DiscordUser entity.
// If the DiscordUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiscordUserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *DiscordUserMutation) ResetUsername() {
	m.username = nil
}

// SetGlobalName sets the "global_name" field.
func (m *DiscordUserMutation) SetGlobalName(s string) {
	m.global_name = &s
}

// GlobalName returns the value of the "global_name" field in the mutation.
func (m *DiscordUserMutation) GlobalName() (r string, exists bool) {
	v := m.global_name
	if v == nil {
		return
	}
	return *v, true
}

// OldGlobalName returns the old "global_name" field's value of the DiscordUser entity.
// If the DiscordUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiscordUserMutation) OldGlobalName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGlobalName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGlobalName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGlobalName: %w", err)
	}
	return oldValue.GlobalName, nil
}

// ResetGlobalName resets all changes to the "global_name" field.
func (m *DiscordUserMutation) ResetGlobalName() {
	m.global_name = nil
}

// AddMessageIDs adds the "messages" edge to the DiscordMessage entity by ids.
func (m *DiscordUserMutation) AddMessageIDs(ids ...string) {
	if m.messages == nil {
		m.messages = make(map[string]struct{})
	}
	for i := range ids {
		m.messages[ids[i]] = struct{}{}
	}
}

// ClearMessages clears the "messages" edge to the DiscordMessage entity.
func (m *DiscordUserMutation) ClearMessages() {
	m.clearedmessages = true
}

// MessagesCleared reports if the "messages" edge to the DiscordMessage entity was cleared.
func (m *DiscordUserMutation) MessagesCleared() bool {
	return m.clearedmessages
}

// RemoveMessageIDs removes the "messages" edge to the DiscordMessage entity by IDs.
func (m *DiscordUserMutation) RemoveMessageIDs(ids ...string) {
	if m.removedmessages == nil {
		m.removedmessages = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.messages, ids[i])
		m.removedmessages[ids[i]] = struct{}{}
	}
}

// RemovedMessages returns the removed IDs of the "messages" edge to the DiscordMessage entity.
func (m *DiscordUserMutation) RemovedMessagesIDs() (ids []string) {
	for id := range m.removedmessages {
		ids = append(ids, id)
	}
	return
}

// MessagesIDs returns the "messages" edge IDs in the mutation.
func (m *DiscordUserMutation) MessagesIDs() (ids []string) {
	for id := range m.messages {
		ids = append(ids, id)
	}
	return
}

// ResetMessages resets all changes to the "messages" edge.
func (m *DiscordUserMutation) ResetMessages() {
	m.messages = nil
	m.clearedmessages = false
	m.removedmessages = nil
}

// Where appends a list predicates to the DiscordUserMutation builder.
func (m *DiscordUserMutation) Where(ps ...predicate.DiscordUser) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DiscordUserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DiscordUserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DiscordUser, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DiscordUserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DiscordUserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DiscordUser).
func (m *DiscordUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DiscordUserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.username != nil {
		fields = append(fields, discorduser.FieldUsername)
	}
	if m.global_name != nil {
		fields = append(fields, discorduser.FieldGlobalName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DiscordUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case discorduser.FieldUsername:
		return m.Username()
	case discorduser.FieldGlobalName:
		return m.GlobalName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DiscordUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case discorduser.FieldUsername:
		return m.OldUsername(ctx)
	case discorduser.FieldGlobalName:
		return m.OldGlobalName(ctx)
	}
	return nil, fmt.Errorf("unknown DiscordUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DiscordUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case discorduser.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case discorduser.FieldGlobalName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGlobalName(v)
		return nil
	}
	return fmt.Errorf("unknown DiscordUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DiscordUserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DiscordUserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DiscordUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DiscordUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DiscordUserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DiscordUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DiscordUserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DiscordUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DiscordUserMutation) ResetField(name string) error {
	switch name {
	case discorduser.FieldUsername:
		m.ResetUsername()
		return nil
	case discorduser.FieldGlobalName:
		m.ResetGlobalName()
		return nil
	}
	return fmt.Errorf("unknown DiscordUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DiscordUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.messages != nil {
		edges = append(edges, discorduser.EdgeMessages)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DiscordUserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case discorduser.EdgeMessages:
		ids := make([]ent.Value, 0, len(m.messages))
		for id := range m.messages {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DiscordUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedmessages != nil {
		edges = append(edges, discorduser.EdgeMessages)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DiscordUserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case discorduser.EdgeMessages:
		ids := make([]ent.Value, 0, len(m.removedmessages))
		for id := range m.removedmessages {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DiscordUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedmessages {
		edges = append(edges, discorduser.EdgeMessages)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DiscordUserMutation) EdgeCleared(name string) bool {
	switch name {
	case discorduser.EdgeMessages:
		return m.clearedmessages
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DiscordUserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown DiscordUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DiscordUserMutation) ResetEdge(name string) error {
	switch name {
	case discorduser.EdgeMessages:
		m.ResetMessages()
		return nil
	}
	return fmt.Errorf("unknown DiscordUser edge %s", name)
}
