// Code generated by ent, DO NOT EDIT.

package discordmessage

import (
	"sev0/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldContainsFold(FieldID, id))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldContent, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldAuthorID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldTimestamp, v))
}

// EditedTimestamp applies equality check predicate on the "edited_timestamp" field. It's identical to EditedTimestampEQ.
func EditedTimestamp(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldEditedTimestamp, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldContainsFold(FieldContent, v))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorIDContains applies the Contains predicate on the "author_id" field.
func AuthorIDContains(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldContains(FieldAuthorID, v))
}

// AuthorIDHasPrefix applies the HasPrefix predicate on the "author_id" field.
func AuthorIDHasPrefix(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldHasPrefix(FieldAuthorID, v))
}

// AuthorIDHasSuffix applies the HasSuffix predicate on the "author_id" field.
func AuthorIDHasSuffix(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldHasSuffix(FieldAuthorID, v))
}

// AuthorIDEqualFold applies the EqualFold predicate on the "author_id" field.
func AuthorIDEqualFold(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEqualFold(FieldAuthorID, v))
}

// AuthorIDContainsFold applies the ContainsFold predicate on the "author_id" field.
func AuthorIDContainsFold(v string) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldContainsFold(FieldAuthorID, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLTE(FieldTimestamp, v))
}

// EditedTimestampEQ applies the EQ predicate on the "edited_timestamp" field.
func EditedTimestampEQ(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldEQ(FieldEditedTimestamp, v))
}

// EditedTimestampNEQ applies the NEQ predicate on the "edited_timestamp" field.
func EditedTimestampNEQ(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNEQ(FieldEditedTimestamp, v))
}

// EditedTimestampIn applies the In predicate on the "edited_timestamp" field.
func EditedTimestampIn(vs ...time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldIn(FieldEditedTimestamp, vs...))
}

// EditedTimestampNotIn applies the NotIn predicate on the "edited_timestamp" field.
func EditedTimestampNotIn(vs ...time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldNotIn(FieldEditedTimestamp, vs...))
}

// EditedTimestampGT applies the GT predicate on the "edited_timestamp" field.
func EditedTimestampGT(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGT(FieldEditedTimestamp, v))
}

// EditedTimestampGTE applies the GTE predicate on the "edited_timestamp" field.
func EditedTimestampGTE(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldGTE(FieldEditedTimestamp, v))
}

// EditedTimestampLT applies the LT predicate on the "edited_timestamp" field.
func EditedTimestampLT(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLT(FieldEditedTimestamp, v))
}

// EditedTimestampLTE applies the LTE predicate on the "edited_timestamp" field.
func EditedTimestampLTE(v time.Time) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.FieldLTE(FieldEditedTimestamp, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DiscordMessage {
	return predicate.DiscordMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.DiscordUser) predicate.DiscordMessage {
	return predicate.DiscordMessage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DiscordMessage) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DiscordMessage) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DiscordMessage) predicate.DiscordMessage {
	return predicate.DiscordMessage(sql.NotPredicates(p))
}
