// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DiscordMessage is the predicate function for discordmessage builders.
type DiscordMessage func(*sql.Selector)

// DiscordUser is the predicate function for discorduser builders.
type DiscordUser func(*sql.Selector)
